create extension if not exists pgcrypto;

-- =========================================================
-- PROFILES: add referral fields safely
-- =========================================================
alter table public.profiles
  add column if not exists referral_code text,
  add column if not exists referred_by uuid references public.profiles(id) on delete set null,
  add column if not exists signup_bonus_awarded boolean not null default false,
  add column if not exists jb_points integer not null default 0;

create unique index if not exists profiles_referral_code_unique_idx
  on public.profiles (referral_code)
  where referral_code is not null;

create index if not exists profiles_referred_by_idx
  on public.profiles (referred_by);

-- =========================================================
-- REFERRAL / COIN HISTORY
-- =========================================================
create table if not exists public.coin_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  amount integer not null default 0,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists coin_history_user_id_idx
  on public.coin_history (user_id);

create index if not exists coin_history_created_at_idx
  on public.coin_history (created_at desc);

create table if not exists public.referral_events (
  id bigint generated by default as identity primary key,
  inviter_id uuid references public.profiles(id) on delete set null,
  invited_user_id uuid references public.profiles(id) on delete set null,
  referral_code text,
  referral_valid boolean not null default false,
  inviter_reward integer not null default 0,
  invited_reward integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists referral_events_inviter_id_idx
  on public.referral_events (inviter_id);

create index if not exists referral_events_invited_user_id_idx
  on public.referral_events (invited_user_id);

-- =========================================================
-- HELPER: generate unique referral code
-- =========================================================
create or replace function public.generate_unique_referral_code()
returns text
language plpgsql
as $$
declare
  candidate text;
begin
  loop
    candidate := upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 10));
    exit when not exists (
      select 1
      from public.profiles
      where referral_code = candidate
    );
  end loop;

  return candidate;
end;
$$;

-- =========================================================
-- BACKFILL missing referral codes for existing users
-- =========================================================
update public.profiles
set referral_code = public.generate_unique_referral_code()
where referral_code is null or btrim(referral_code) = '';

-- =========================================================
-- MAIN FUNCTION:
-- 1) ensure new user has referral code
-- 2) give signup bonus once
-- 3) if referral code is valid, reward inviter once
-- 4) write coin history + referral event
-- =========================================================
create or replace function public.claim_signup_and_referral_bonus(
  p_new_user_id uuid,
  p_referral_code text default null,
  p_signup_bonus integer default 35,
  p_referral_bonus integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_profile public.profiles%rowtype;
  v_inviter public.profiles%rowtype;
  v_clean_code text;
  v_awarded_signup boolean := false;
  v_awarded_referral boolean := false;
begin
  if p_new_user_id is null then
    return jsonb_build_object(
      'ok', false,
      'message', 'Missing new user id'
    );
  end if;

  -- lock new user profile row
  select *
  into v_new_profile
  from public.profiles
  where id = p_new_user_id
  for update;

  if not found then
    return jsonb_build_object(
      'ok', false,
      'message', 'Profile not found'
    );
  end if;

  -- ensure referral code exists for the new user
  if v_new_profile.referral_code is null or btrim(v_new_profile.referral_code) = '' then
    update public.profiles
    set referral_code = public.generate_unique_referral_code()
    where id = p_new_user_id;

    select *
    into v_new_profile
    from public.profiles
    where id = p_new_user_id
    for update;
  end if;

  -- signup bonus only once
  if coalesce(v_new_profile.signup_bonus_awarded, false) = false then
    update public.profiles
    set
      jb_points = coalesce(jb_points, 0) + greatest(p_signup_bonus, 0),
      signup_bonus_awarded = true
    where id = p_new_user_id;

    insert into public.coin_history (
      user_id,
      event_type,
      amount,
      description,
      metadata
    )
    values (
      p_new_user_id,
      'signup_bonus',
      greatest(p_signup_bonus, 0),
      'Signup bonus',
      jsonb_build_object('source', 'signup')
    );

    v_awarded_signup := true;
  end if;

  -- referral handling
  v_clean_code := nullif(upper(btrim(coalesce(p_referral_code, ''))), '');

  if v_clean_code is not null then
    select *
    into v_inviter
    from public.profiles
    where referral_code = v_clean_code
    for update;

    if found and v_inviter.id <> p_new_user_id and v_new_profile.referred_by is null then
      update public.profiles
      set referred_by = v_inviter.id
      where id = p_new_user_id;

      update public.profiles
      set jb_points = coalesce(jb_points, 0) + greatest(p_referral_bonus, 0)
      where id = v_inviter.id;

      insert into public.coin_history (
        user_id,
        event_type,
        amount,
        description,
        metadata
      )
      values (
        v_inviter.id,
        'referral_signup_bonus',
        greatest(p_referral_bonus, 0),
        'Referral signup bonus',
        jsonb_build_object(
          'invited_user_id', p_new_user_id,
          'referral_code', v_clean_code
        )
      );

      insert into public.referral_events (
        inviter_id,
        invited_user_id,
        referral_code,
        referral_valid,
        inviter_reward,
        invited_reward
      )
      values (
        v_inviter.id,
        p_new_user_id,
        v_clean_code,
        true,
        greatest(p_referral_bonus, 0),
        case when v_awarded_signup then greatest(p_signup_bonus, 0) else 0 end
      );

      v_awarded_referral := true;
    else
      insert into public.referral_events (
        inviter_id,
        invited_user_id,
        referral_code,
        referral_valid,
        inviter_reward,
        invited_reward
      )
      values (
        case when found then v_inviter.id else null end,
        p_new_user_id,
        v_clean_code,
        false,
        0,
        case when v_awarded_signup then greatest(p_signup_bonus, 0) else 0 end
      );
    end if;
  else
    insert into public.referral_events (
      inviter_id,
      invited_user_id,
      referral_code,
      referral_valid,
      inviter_reward,
      invited_reward
    )
    values (
      null,
      p_new_user_id,
      null,
      false,
      0,
      case when v_awarded_signup then greatest(p_signup_bonus, 0) else 0 end
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'signup_bonus_awarded', v_awarded_signup,
    'referral_bonus_awarded', v_awarded_referral
  );
end;
$$;

grant execute on function public.claim_signup_and_referral_bonus(uuid, text, integer, integer) to anon;
grant execute on function public.claim_signup_and_referral_bonus(uuid, text, integer, integer) to authenticated;

grant execute on function public.generate_unique_referral_code() to anon;
grant execute on function public.generate_unique_referral_code() to authenticated;

-- =========================================================
-- RLS
-- =========================================================
alter table public.coin_history enable row level security;
alter table public.referral_events enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'coin_history'
      and policyname = 'coin_history_select_own'
  ) then
    create policy coin_history_select_own
      on public.coin_history
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'referral_events'
      and policyname = 'referral_events_select_own'
  ) then
    create policy referral_events_select_own
      on public.referral_events
      for select
      to authenticated
      using (
        auth.uid() = inviter_id
        or auth.uid() = invited_user_id
      );
  end if;
end $$;